env: "dev"
storage_path: "postgresql://srmt:srmt@localhost:5432/srmt?sslmode=disable"
log_path: "mongodb://srmt:srmt@localhost:27017/srmt?authSource=admin"
migrations_path: "file://./migrations"
http_server:
  address: "localhost:9010"
  timeout: 4s
  idle_timeout: 60s