env: "local"
storage_path: "./data/srmt_db.sqlite"
#log_path: "mongodb://srmt:srmt@localhost:27017/srmt?authSource=admin"
migrations_path: "file://./migrations"
http_server:
  address: ":9010"
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret: "pAcmKVrB5AWhOi/162ehskTyjftPzpb6nk4GCwrkH6Q="
  access_timeout: 3h
  refresh_timeout: 24h