apiVersion: v1
kind: Service
metadata:
  name: ac-integration
  labels:
    app: ac-integration
spec:
  type: ClusterIP
  selector:
    app: ac-integration
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
