apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - sealed-config.yaml

labels:
  - pairs:
      app.kubernetes.io/env: dev

images:
  - name: ac-integration
    newName: suxa/ac-integration
    newTag: latest

replicas:
  - name: ac-integration
    count: 1

patches:
  - path: service-nodeport.yaml
