apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - sealed-config.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/env: prod

images:
  - name: ac-integration
    newName: suxa/ac-integration
    newTag: latest

replicas:
  - name: ac-integration
    count: 2

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ac-integration
      spec:
        template:
          spec:
            containers:
              - name: ac-integration
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "200m"
                  limits:
                    memory: "512Mi"
                    cpu: "1000m"
